NLayerApp.Web/Models/Shared/CountryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NLayerApp.Web.Models.Shared
{
    public class CountryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

NLayerApp.Web/Controllers/BookController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NLayerApp.Services.Common.Authors;
using NLayerApp.Services.Common.Books;
using NLayerApp.Services.Common.Books.Dto;
using NLayerApp.Services.Common.Categories;
using NLayerApp.Web.Models.Book;
using Omu.ValueInjecter;

namespace NLayerApp.Web.Controllers
{
  public class BookController : Controller
  {
    private readonly IBookService bookService;
    private readonly IAuthorService authorService;
    private readonly ICategoryService categoryService;

    public BookController(IBookService bookService, IAuthorService authorService, ICategoryService categoryService)
    {
      this.bookService = bookService;
      this.authorService = authorService;
      this.categoryService = categoryService;
    }

    [HttpGet]
    public ActionResult Index()
    {
      var detailedBookDtos = bookService.GetDetailedBooks();

      var bookModels = new List<BookModel>();
      foreach (var detailedBookDto in detailedBookDtos)
      {
        var bookModel = new BookModel();
        bookModel.InjectFrom(detailedBookDto);
        bookModels.Add(bookModel);
      }

      return View(bookModels);
    }

    [HttpGet]
    public ActionResult Details(int id)
    {
      if (id < 1) return RedirectToAction("Index"); //If the ID is negative, we redirect the user from the start and we save a trip to the database

      var bookDto = bookService.GetBookById(id);
      if (bookDto == null) return RedirectToAction("Index");

      var authorDto = authorService.GetAuthorById(bookDto.AuthorId);
      if (authorDto == null) return RedirectToAction("Index");

      var categoryDto = categoryService.GetCategoryById(bookDto.CategoryId);
      if (categoryDto == null) return RedirectToAction("Index");

      var bookModel = new BookModel
      {
        Author = authorDto.Name,
        Category = categoryDto.Name,
        IsDeleted = bookDto.IsDeleted,
        Title = bookDto.Title,
        Id = bookDto.Id
      };

      return View(bookModel);
    }

    [HttpGet]
    public ActionResult Create()
    {
      var createBookModel = new CreateBookModel();

      var authors = authorService.GetNonDeletedAuthors();
      var categories = categoryService.GetNonDeletedCategories();

      createBookModel.Authors = authors.Select(author => new SelectListItem { Value = author.Id.ToString(), Text = author.Name }).ToList();
      createBookModel.Categories = categories.Select(category => new SelectListItem { Value = category.Id.ToString(), Text = category.Name }).ToList();

      return View(createBookModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(CreateBookModel book)
    {
      if (!ModelState.IsValid) return View(book);

      var bookDto = new BookDto
      {
        AuthorId = book.AuthorId,
        CategoryId = book.CategoryId,
        IsDeleted = book.IsDeleted,
        Title = book.Title
      }; //Because the properties have all the same types and names, we could just use bookDto.InjectFrom(book).

      bookService.CreateBook(bookDto);
      return RedirectToAction("Index");
    }

    [HttpGet]
    public ActionResult Edit(int id)
    {
      if (id < 1) return RedirectToAction("Index"); //If the ID is negative, we redirect the user from the start and we save a trip to the database

      var bookDto = bookService.GetBookById(id);
      if (bookDto == null) return RedirectToAction("Index");

      var authors = authorService.GetNonDeletedAuthors();
      var categories = categoryService.GetNonDeletedCategories();

      var editBookModel = new EditBookModel
      {
        AuthorId = bookDto.AuthorId,
        CategoryId = bookDto.CategoryId,
        Id = bookDto.Id,
        IsDeleted = bookDto.IsDeleted,
        Title = bookDto.Title,
        Authors = authors.Select(author => new SelectListItem { Value = author.Id.ToString(), Text = author.Name }).ToList(),
        Categories = categories.Select(category => new SelectListItem { Value = category.Id.ToString(), Text = category.Name }).ToList()
      };

      return View(editBookModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, EditBookModel book)
    {
      if (id < 1) return RedirectToAction("Index"); //If the ID is negative, we redirect the user from the start and we save a trip to the database

      var bookDto = bookService.GetBookById(id);
      if (bookDto == null) return RedirectToAction("Index");

      bookDto.InjectFrom(book);
      bookService.UpdateBook(bookDto);

      return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public ActionResult Delete(int id)
    {
      if (id < 1) return RedirectToAction("Index"); //If the ID is negative, we redirect the user from the start and we save a trip to the database

      var bookDto = bookService.GetBookById(id);
      if (bookDto == null) return RedirectToAction("Index");

      var authorDto = authorService.GetAuthorById(bookDto.AuthorId);
      if (authorDto == null) return RedirectToAction("Index");

      var categoryDto = categoryService.GetCategoryById(bookDto.CategoryId);
      if (categoryDto == null) return RedirectToAction("Index");

      var bookModel = new BookModel
      {
        Author = authorDto.Name,
        Category = categoryDto.Name,
        IsDeleted = bookDto.IsDeleted,
        Title = bookDto.Title,
        Id = bookDto.Id
      };

      return View(bookModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
      if (id < 1) return RedirectToAction("Index"); //If the ID is negative, we redirect the user from the start and we save a trip to the database

      var bookDto = bookService.GetBookById(id);
      if (bookDto == null) return RedirectToAction("Index");

      bookDto.IsDeleted = true;
      bookService.UpdateBook(bookDto);

      return RedirectToAction(nameof(Index));
    }
  }
}

NLayerApp.Web/Views/Shared/_Layout.cshtml
@{
  var test = "123";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NLayerApp.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <span>@test</span>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NLayerApp.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Book" asp-action="Index">Books</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
              @if (Context.User.Identity.IsAuthenticated)
              {
                  <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                    <ul class="nav navbar-nav navbar-right">
                      <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index" title="Manage">Hello @Context.User.Identity.Name!</a>
                      </li>
                      <li>
                        <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
                      </li>
                    </ul>
                  </form>
              }
              else
              {
                  <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Account" asp-action="Register" asp-route-returnUrl="@Context.Request.Path">Register</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">Log in</a></li>
                  </ul>
              }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - NLayerApp.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>